import argparse
import os

from typing import Dict, Any, Optional, List

from src.scheduler.schedule_controller import EpochScheduler, EpochConfig
from src.batch.operations_of_Batch import create_batch
from src.batch.batch_class import Batch
from src.utils.utils import get_logger

logger = get_logger(__name__)

def main():
    parser = argparse.ArgumentParser(description="Generate harnesses for those functions that were modified or added in the given program.")

    # args_group = parser.add_mutually_exclusive_group(required=True)

    #TODO: 当前的生成harness的粒度是函数级别的，后续需要将这个粒度细化到行级别的
    #TODO: 在utils中添加一个函数，后续目标函数名（或者是源文件行号）处理为包含相关信息的对应列表
    #TODO: 当前的所有操作都是单线程的，后续考虑将这些操作做成多线程

    parser.add_argument(
        "--lib_name", "-l",
        type=str,
        help="The name of the library to generate harnesses for. "
    )

    parser.add_argument(
        "--function-name", "-f",
        #nargs='+',
        type=str,
        required=True,
        help="The names of the target function to generate a harness for."
    )

    parser.add_argument(
        "--project-path", "-p",
        type=str,
        required=True,
        help="The path to the project directory."
    )

    parser.add_argument(
        "--dot-file", "-d",
        type=str,
        required=True
    )

    parser.add_argument(
        "--compile-commands-path", "-c",
        type=str,
        help="The path to the compile_commands.json file in target project."
    )

    parser.add_argument(
        "--seeds-path", "-s",
        type=str,
        help="The path to the seed inputs for fuzzing provided by user."
    )

    parser.add_argument(
        "--cve-hints-path", "-ch",
        type=str,
        help="The path to the cve_hints.json file generated by cve_helper, which can provide optional hints for fuzzing based on CVE intel or user-provided rules."
    )       # cve_helper support, optional

    parser.add_argument(
        "--fusion-keyword", "-k",
        type=str,
        default="",
        help="Keyword for nm -u symbol extraction in harness_fusion (e.g., TIFF, xml). Overrides lib_name-derived default."
    )

    args = parser.parse_args()

    #### fxm debug  
    # scheduler = EpochScheduler(config=EpochConfig())
    # scheduler.run("c0577b4a-0d23-422d-9815-0742cb6638ef")
    #### fxm debug

    assert os.path.isdir(args.project_path), f"Project path {args.project_path} is not a valid directory."
    assert os.path.exists(args.project_path), f"Project path {args.project_path} does not exist."
    assert os.path.isfile(args.dot_file), f"Dot file {args.dot_file} does not exist."

    lib_name = args.lib_name
    source_dir = args.project_path
    dot_file = args.dot_file
    target_funcs = args.function_name
    compile_commands_path = args.compile_commands_path
    seeds_path = args.seeds_path
    cve_hints_path = args.cve_hints_path    # cve_helper support
    if args.fusion_keyword:
        os.environ["AFL_FUSION_KW"] = args.fusion_keyword

    # create batch (harness skeletons generation + harness plans generation + harness code generation)
    batch_id = create_batch(lib_name=lib_name, source_dir=source_dir, dot_file=dot_file, target_funcs=target_funcs, compile_commands_path=compile_commands_path, cve_hints_path=cve_hints_path)
    
    #start fuzzing, use Batch class to manage the fuzzing processes
    scheduler = EpochScheduler(config=EpochConfig())
    if seeds_path:
        scheduler.run(batch_id, seeds_path=seeds_path)
    else:
        scheduler.run(batch_id)


if __name__ == "__main__":
    main()

"""
the aggregate_for_chain function from src/static_analyze/aggregator.py
the name chain and the ccdb_path parameters are required. Other parameters are optional, but set these optional parameters to argparse later

def aggregate_for_chain(name_chain: List[str], 
                        ccdb_path: str, 
                        include_headers: bool = False, 
                        system_includes: bool = False,
                        bitmask_require_op: bool = True,
                        max_guards_per_node: int = 4,
                        vendor_prefixes: Optional[List[str]] = None,
                        infer_vendor_prefixes: bool = True,
                        vendor_prefix_threshold: float = 0.25,
                        min_vendor_len: int = 2
                        ) -> Dict:
"""
